# Ctrl-A as main prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix 

# window numbering starts with 1
set -g base-index 1
setw -g pane-base-index 1

# renumber windows
set-option -g renumber-windows on

#Does not work! fix nvim line numbers
set-option -g focus-events

# set -g default-terminal "xterm-screen-256color"
# set -g default-terminal "screen-265color"
# set -g default-terminal "tmux-265color"
# set-option -g xterm-keys on

#Ctrl+a, Ctrl+a to swap between windows
bind-key C-a last-window

#Ctrl+a a to send Ctrl+a
bind-key a send-key C-a
bind-key A send-key C-a

#color
set -g status-style bg=gray,fg=black

#for neovim
set-option -g focus-events on

#for yazi previews
set -g allow-passthrough on
# set -ga update-environment TERM
# set -ga update-environment TERM_PROGRAM


# # Status bar example style (light blue background for unformatted status area)
# set -g status-style "bg=brightblue,fg=black"
# set -g status-left-length 50
# set -g status-right-length 50
#
# # Left side: <cyan on black> hostname </cyan on black><gray on black>[session-name]</gray on black>
# set -g status-left "#[fg=cyan,bg=black] #h #[fg=brightblack,bg=black][#S]#[fg=black,bg=brightblue] "
#
# # Right side: <cyan on black> date time iso format </cyan on black>
# set -g status-right "#[fg=cyan,bg=black] %Y-%m-%d %H:%M "
# # set -g status-interval 1
#
# # Inactive tabs: <black fg> inactive tab </black fg> on light blue bg
# set -g window-status-style "fg=black,bg=brightblue"
# set -g window-status-format "#I:#W#{?#F,#F, }"
#
# # Active window: <black on cyan> active window </black on cyan>
# set -g window-status-current-style "fg=black,bg=cyan"
# set -g window-status-current-format "#I:#W#{?#F,#F, }"


# attempt to load local config
source-file -q ~/.tmux.conf.local

